include:
  [
    "_pages",
    "_redirects",
    "robots.txt",
  ]

sass:
  style: compressed
  sass_dir: _scss

plugins:
  - jekyll-sitemap

url: "https://ebti.com.ua"

exclude:
  - README.md
  - node_modules/